# -*- coding: utf-8 -*-
"""Untitled104.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c78PbxFJUvEZ2lVtHc4jRfO4D1vjyFqf
"""

!pip install lxml
!pip install requests
!pip install beautifulsoup4
!pip install fake_useragent
!pip install tinvest



import requests
from bs4 import BeautifulSoup
from fake_useragent import UserAgent
import base64 
UserAgent().chrome
while 1 <2:
  url1 = "https://ir.uipath.com/financials/quarterly-results"
  url2 = ""

  page = requests.get(url1, headers={'User-Agent': UserAgent().chrome})
  soup = BeautifulSoup(page.text, "html.parser")
  soup = soup.find_all('main')
  soup = str(soup)
  #print(soup)
  #<div class="result-line"> найти после этого 
  b = ""
  def resline(i):
    j = i
    k = 1
    b = ""
    for k in range(len("a href=")): #"result-line" 
      b = b + soup[i]
      i += 1
      k += 1
    i = j
    return b
  i = 0

  while i <= len(soup)-1:
    if resline(i) == "a href=":
      i += 7 # так как через 7 элементов начинается ссылка
      while soup[i] != ">":
        url2 = url2 + soup[i]
        i += 1
      break
    i += 1 

    
  #print(url1)

  url0 = ""
  i = 1

  while i <= len(url2)-2:
    url0 = url0 + url2[i] 
    i += 1




  # print(url0)

  page1 = requests.get(url0, headers={'User-Agent': UserAgent().chrome})
  soup = BeautifulSoup(page1.text, "html.parser")
  soup = soup.find_all('tr')
  soup = str(soup)

  # print(soup)
  j = 0
  def revenues(i):
    k = 1
    b = ""
    for k in range(len("bwalignr bwcellpmargin")):  
      b = b + soup[i]
      i += 1
      k += 1
    i = j
    return b

  i = 0


  rev = "" # revenue
  i = 0
  n = 1 #13 графа в таблице есть искомое значение
  for i in range(len(soup)):
    if revenues(i) == "bwalignr bwcellpmargin":
      if n == 13:
        i = i + len("bwalignr bwcellpmargin") + 2
        while soup[i] != "<":
          rev = rev + soup[i]
          i += 1
        break
      else:
        n += 1      
      

  #print(rev)
  rev = rev.replace(' ','   ')

  i = 0
  z = 0 
  #поиск запятой
  reva = ""
  for i in range(len(rev)):
    if rev[i] == ",":
      reva = reva + "."
    else:
      reva = reva + rev[i]


  reva = float(reva) 
  if reva > 195.521:
    f = 1
    print("Buy")
  elif reva < 195.521:
    f = 1
    print(Sell)
  if f == 1:
    print(reva)
    break
  #https://ir.uipath.com/news/detail/179/uipath-reports-second-quarter-fiscal-2022-financial-results/
  #bwalignr bwcellpmargin
  print("-------")
  n = 1